name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master
      - python-oop
      - python-typing
      - python-basic

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pycodestyle
        run: pip install pycodestyle

      - name: Run pycodestyle
        run: pycodestyle . --ignore=E501,W504

